title: "Jyothiswaroop Makala"
tagline: "Curious about Statistics and Finance"
description: "Personal portfolio and blog"
url: "https://jrmakala.com"
baseurl: ""

avatar: /assets/img/avatar.jpg

social:
  name: Jyothiswaroop Makala
  email: jrmakala@ucdavis.edu
  links:
    - https://github.com/jyothiswaroopVoid
    - https://www.linkedin.com/in/jyomakala/

github:
  username: jyothiswaroopVoid

linkedin:
  username: jyomakala

theme_mode: light

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
